// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWWv2mY2J_Eu_ebwirbEDu4rECAzJoTg',
    appId: '1:870118002530:android:8271afb28f5d2556e6e63b',
    messagingSenderId: '870118002530',
    projectId: 'crud-47463',
    storageBucket: 'crud-47463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGASLUgxb9Gu7jY3tQY9skCjgfoFvIbt4',
    appId: '1:870118002530:ios:a119a6138279f4a6e6e63b',
    messagingSenderId: '870118002530',
    projectId: 'crud-47463',
    storageBucket: 'crud-47463.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2wVGX4HasqIYMLdJlNnlzNnoXrFDCCIA',
    appId: '1:870118002530:web:956762a733fd0edce6e63b',
    messagingSenderId: '870118002530',
    projectId: 'crud-47463',
    authDomain: 'crud-47463.firebaseapp.com',
    storageBucket: 'crud-47463.appspot.com',
    measurementId: 'G-FX9XLC80GJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGASLUgxb9Gu7jY3tQY9skCjgfoFvIbt4',
    appId: '1:870118002530:ios:a119a6138279f4a6e6e63b',
    messagingSenderId: '870118002530',
    projectId: 'crud-47463',
    storageBucket: 'crud-47463.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2wVGX4HasqIYMLdJlNnlzNnoXrFDCCIA',
    appId: '1:870118002530:web:74f687038b0b5cf8e6e63b',
    messagingSenderId: '870118002530',
    projectId: 'crud-47463',
    authDomain: 'crud-47463.firebaseapp.com',
    storageBucket: 'crud-47463.appspot.com',
    measurementId: 'G-BWKGQT284H',
  );

}